name: Check build
on: [push]
jobs:
  dependencies:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - run: npm run build
